import styles from "./page.module.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

export default function Home() {
  return (
    <div className={styles.page}>
      <div className={styles.content_container}>
        {/* navbar goes here */}
        <Navbar />
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        <div>asd</div>
        {/* footer goes here */}
        <Footer />
      </div>
    </div>
  );
}
